"""
generate HTML for main page dynamically from an executable Python script,
not a precoded HTML file; this lets us import the expected input field name
and the selection table values from a common Python module file; changes in 
either now only have to be made in one place, the Python module file;
"""

REPLY = """
<html><title>languages2</title>
<body>
<h1>Hello World selector</h1>
<p>Similar to file <a href="../langages.html">languages.html</a>, but
this page is dynamically generated by a Python CGI script, using 
selection list and input field names imported from a common Python
module on the server. Only the common module must be maintained as 
new languages are added, because it is shared with the reply script.
</p>
To see the code that generates this page and the reply, click
<a href="getfile.py?filename=cgi-bin\languages2.py">here</a>,
<a href="getfile.py?filename=cgi-bin\languagesreply.py">here</a>,
<a href="getfile.py?filename=cgi-bin\languages2common.py">here</a>, and
<a href="getfile.py?filename=cgi-bin\\formMockup.py">here</a>.</p>
<hr>
<form method="POST" action="languages2reply.py">
    <p><B>Select a programming language:</B></p>
    <p><select name="%s">
        <option>All</option>
        %s
        <option>Other</option>
    </select></p>
    <p><input type="Submit"</p>
</form>
</body>
</html>
"""

from languages2common import hellos, inputkey

options = []
for lang in hellos:
    options.append('<option>' + lang)
options = '\n\t'.join(options)
print(REPLY % (inputkey, options))



























